name: CI

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '1.8'
    - name: Cache gradle
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Install Kerberos lib
      run: sudo apt-get install libkrb5-dev
    - name: Build components
      run: TERM=dumb ./build-support/jenkins/build.sh
